### ISSUE TITLE
MissingFieldException crash

### ISSUE THREAD

**Issue by LPeter1997** [Draco-lang/Compiler#306]
```
val line = ReadLine();
val parts = line.Split(",", StringSplitOptions.TrimEntries);
```
error:
```
Unhandled exception. System.MissingFieldException: Field not found: 'System.StringSplitOptions.None'.
   at DracoTest.read_coords()
   at DracoTest.main() in C:/Development/DracoTest/main.draco:line 44
```

**Comment by LPeter1997** [comment]
`StringSplitOptions` is an enum, we'll need to implement enums support. Probably can wait until DUs
